name: vrs deploye

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout backend
      uses: actions/checkout@v3

    - name: Build and push backend image
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker build -t nushan2000/vrs:backend-latest .
        docker push nushan2000/vrs:backend-latest

    - name: SSH and deploy on VPS
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: 192.248.50.253
        username: vrsuser
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd ~/vrs
          echo "${{ secrets.ENV_FILE }}" > .env
          docker-compose pull
          docker-compose up -d
