name: vrs deploye

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout backend
      uses: actions/checkout@v3
      with:
        repository: nushan2000/VRMSbackend

    - name: Build and push backend image
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build -t nushan2000/vrs:backend-latest .
          docker push nushan2000/vrs:backend-latest

    - name: SSH and deploy on VPS
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: 10.50.227.121
        username: vrsuser
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd ~/vrs
          echo "${{ secrets.ENV_FILE }}" > .env
          docker-compose pull
          docker-compose up -d
